### ISSUE TITLE
Would like to be able to use Duo passcodes

### ISSUE THREAD

**Issue by davidmankin** [atlassian/kubetoken#19]
Currently my "default" Duo auth mechanism is Push to my phone. 

But sometimes I want to use a Duo passcode (e.g. when I have Yubikey available).

I'd like a `--passcode` flag to be able to pass a passcode to token.

**Comment by davidmankin** [comment]
Please assign this to me and I'll contribute the fix.

**Comment by patrickshan** [comment]
Close this issue since kubetoken is no longer maintained.
